testinfo:
  case_suite: getCopywriterConfigRemind28093_test
  descrpiton: 文案是否不再提醒
  module_class: Test28093
premise: ''
set_up: ''
tear_down: ''
test_case:
- test_name: ''
  info: 文案是否不再提醒
  mark: ''
  method: POST
  url: /pf-lite/api/settings/getCopywriterConfigRemind
  headers:
    Authorization: $token
  timeout: 8
  params: {}
  data: ''
  files: ''
  json: ''
  status: ''
  extract: ''
  expects: ''
