testinfo:
  case_suite: refreshConfig28302_test
  descrpiton: 刷新配置
  module_class: Test28302
premise: ''
set_up: ''
tear_down: ''
test_case:
- test_name: ''
  info: 刷新配置
  mark: ''
  method: GET
  url: /pf-lite/api/outApply/refreshConfig
  headers:
    Authorization: $token
  timeout: 8
  params: {}
  data: ''
  files: ''
  json: ''
  status: ''
  extract: ''
  expects: ''
