testinfo:
  case_suite: getConfig28303_test
  descrpiton: 获取配置1
  module_class: Test28303
premise: ''
set_up: ''
tear_down: ''
test_case:
- test_name: ''
  info: 获取配置1
  mark: ''
  method: GET
  url: /pf-lite/api/outApply/getConfig
  headers:
    Authorization: $token
  timeout: 8
  params: {}
  data: ''
  files: ''
  json: ''
  status: ''
  extract: ''
  expects: ''
