url: https://qyapi.weixin.qq.com/cgi-bin/department/list
method: get
params:
  id: {{id}}
  access_token: {{access_token}}
json:
  db_name: 11g239.121
  asset_type: db
  db_type: 272
  instance: orcl
  db_user: system
  db_pwd: oracle
  db_port: 1521
  os_type: 16
  ip: 192.168.239.121
  os_conn_type: 16
  os_user: oracle
  os_pwd: oracle
  os_port: 22
  group_ids: [ $deldb4group ]
